---
# tasks file for ./dotfiles
# vi: ft=ansible

  - name: install ubuntu stuff
    include: "{{ ansible_distribution + '.yml' }}"
    become: true

  - name: setup stuff
    include: setup.yml
    become: false
